import Navbar from '@/components/Navbar'
import Socials from '@/components/Socials'
import Head from 'next/head'
import BackgroundImage from '../public/background.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/alok.png" />
      </Head>
      <div className='w-full h-screen bg-auto bg-no-repeat bg-center' style={{
        backgroundImage: `url(${BackgroundImage.src})`,
        backgroundSize: 'cover',
        backgroundPosition: 'center',
        backgroundRepeat: 'no-repeat'
      }}>
        <Navbar />
        <div className='absolute top-1/2 left-0 transform -translate-y-1/2'>
          <Socials />
        </div>
      </div>
    </>
  )
}
